#!/usr/bin/env bash
set -e # halt script on error

# Setup virtual env
cd pebble-dev/pebble-sdk-$PEBBLE_TOOL-linux64/

virtualenv --no-site-packages .env
source .env/bin/activate
pip install -r requirements.txt
cd ../..

# Pipe 'yes' into pebble tool to accept terms and conditions
yes | ./pebble-dev/pebble-sdk-$PEBBLE_TOOL-linux64/bin/pebble build
./pebble-dev/pebble-sdk-$PEBBLE_TOOL-linux64/bin/pebble release publish
